gui:
  nerdFontsVersion: "3"
  scrollHeight: 2 # how many lines you scroll by
  scrollPastBottom: true # enable scrolling past the bottom
  sidePanelWidth: 0.25 # number from 0 to 1
  expandFocusedSidePanel: true
  mainPanelSplitMode: "flexible"
  theme:
    activeBorderColor:
      - orange
      - bold
  authorColors:
    "Vignesh Iyer": "#FFBD38"
  git:
    branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"
    allBranchesLogCmd: "git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium"
    log:
      order: "topo-order"
      showGraph: "always"
      showWholeGraph: true
